'use client';

import { jsPDF } from 'jspdf';
import type { StudyContent } from '@/types/study';

const PAGE_WIDTH = 210;
const PAGE_HEIGHT = 297;
const MARGIN = 18;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
const BOTTOM = PAGE_HEIGHT - MARGIN;

function toPdfSafeText(value: string): string {
  return value
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^\x20-\x7e]/g, '?');
}

function safeFilename(title: string): string {
  const safeTitle = title
    .replace(/[<>:"/\\|?*\u0000-\u001f]/g, '')
    .replace(/[. ]+$/g, '')
    .trim();
  return `${safeTitle || 'study-guide'}.pdf`;
}

export function downloadStudyNotesPdf(data: StudyContent, title?: string): void {
  const pdf = new jsPDF({ unit: 'mm', format: 'a4' });
  const lineHeight = 5;
  let y = MARGIN;

  const addPage = () => {
    pdf.addPage();
    y = MARGIN;
  };

  const wrap = (text: string, fontSize: number) => {
    pdf.setFontSize(fontSize);
    return pdf.splitTextToSize(toPdfSafeText(text), CONTENT_WIDTH) as string[];
  };

  const drawParagraph = (text: string, fontSize = 10, after = 3) => {
    const lines = wrap(text, fontSize);
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(fontSize);

    for (const line of lines) {
      if (y + lineHeight > BOTTOM) addPage();
      pdf.text(line, MARGIN, y);
      y += lineHeight;
    }
    y += after;
  };

  const drawSection = (heading: string, paragraphs: string[]) => {
    const headingLines = wrap(heading, 13);
    const firstParagraphLines = paragraphs.length > 0 ? wrap(paragraphs[0], 10) : [];
    const minimumBodyHeight = firstParagraphLines.length > 0 ? lineHeight : 0;
    const requiredHeight = headingLines.length * 6 + 3 + minimumBodyHeight;

    if (y + requiredHeight > BOTTOM) addPage();

    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(13);
    for (const line of headingLines) {
      pdf.text(line, MARGIN, y);
      y += 6;
    }
    y += 2;

    paragraphs.forEach((paragraph, index) => {
      drawParagraph(paragraph, 10, index < paragraphs.length - 1 ? 2 : 4);
    });
  };

  const documentTitle = title?.trim() || 'Study Guide';
  const titleLines = wrap(documentTitle, 20);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(20);
  for (const line of titleLines) {
    if (y + 9 > BOTTOM) addPage();
    pdf.text(line, MARGIN, y);
    y += 9;
  }
  y += 2;

  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(9);
  pdf.text('STUDY GUIDE GENERATED BY STUDYDESK', MARGIN, y);
  y += 8;

  drawSection('SUMMARY', [data.summary]);
  drawSection(
    'KEY CONCEPTS',
    data.keyConcepts.map((concept) => `- ${concept.title}: ${concept.explanation}`)
  );
  drawSection(
    'DEFINITIONS',
    data.definitions.map((definition) => `- ${definition.term}: ${definition.definition}`)
  );
  drawSection('IMPORTANT FACTS', data.importantFacts.map((fact) => `- ${fact}`));
  drawSection(
    'FORMULAS',
    data.formulas.length > 0
      ? data.formulas.map((formula) =>
          `- ${formula.name}: ${formula.formula} (${formula.description})`
        )
      : ['None']
  );

  pdf.save(safeFilename(documentTitle));
}
